services:
  nodejs:
    build: ./js-server
    container_name: js-server
    ports:
      - "8199:8199"
    command: node app-express.js
    depends_on:
      - flask
    networks:
      - network1
  flask:
    build: ./python-server
    container_name: python-server
    expose:
      - "5000"
    command: python3 server.py
    networks:
      - network1
networks:
  network1:
    driver: bridge